replicas: 3

image:
  repository: pravega/zookeeper
  tag: 0.2.8
  pullPolicy: IfNotPresent

domainName:
labels: {}
ports: []

pod: {}
  # labels: {}
  # nodeSelector: {}
  # affinity: {}
  # resources: {}
  # tolerations: []
  # env: []
  # annotations: {}
  # securityContext:
  # terminationGracePeriodSeconds: 180

config: {}
  # initLimit: 10
  # tickTime: 2000
  # syncLimit: 2
  # quorumListenOnAllIPs: false

persistence:
<<<<<<< HEAD
  storageClassName: baremetal-csi-sc
  # specifying reclaim policy for PersistentVolumes
  # accepted values - Delete / Retain
=======
  storageClassName: standard
  ## specifying reclaim policy for PersistentVolumes
  ## accepted values - Delete / Retain
>>>>>>> 1039e7a6339eb22c873e3c31901f59a755ca30de
  reclaimPolicy: Delete
  volumeSize: 20Gi

hooks:
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.16.10
  backoffLimit: 10
